app_login/urls.py
from django.urls import path
from . import views

app_name = 'app_login'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

app_store/urls.py
from django.urls import path, include
from .views import product_view_json, shop_view, product_page_view, \
    cart_view_json, cart_add_view_json, cart_del_view_json, cart_view, \
    coupon_check_view, delivery_estimate_view, cart_buy_now_view, cart_remove_view

app_name = 'app_store'

urlpatterns = [
    path('', shop_view, name="shop_view"),
    path('product/', product_view_json, name='product_view_json'),  # JSON список товаров или один товар по id
    path('product/<slug:page>.html', product_page_view, name='product_page_view'),  # Страница товара по slug
    path('product/<int:page>', product_page_view, name='product_page_view_by_id'),  # Страница товара по id
    path('cart/json/', cart_view_json, name='cart_view_json'),  # Корзина
    path('cart/', cart_view, name='cart_view'),
    path('cart/add/<id_product>', cart_add_view_json, name='cart_add_view_json'),
    path('cart/del/<id_product>', cart_del_view_json, name='cart_del_view_json'),
    path('coupon/check/<slug:name_coupon>/', coupon_check_view, name='coupon_check'),
    path('delivery/estimate/', delivery_estimate_view, name='delivery_estimate'),
    path('cart/buy/<str:id_product>', cart_buy_now_view, name="buy_now"),
    path('cart/remove/<str:id_product>', cart_remove_view, name="remove_now"),
]

app_wishlist/urls.py
from django.urls import path
from .views import wishlist_view, wishlist_view_json, wishlist_add_view_json, \
    wishlist_del_view_json, wishlist_remove_view

app_name = 'app_wishlist'

urlpatterns = [
    path('', wishlist_view, name='wishlist_view'),
    path('api/', wishlist_view_json, name='wishlist_view_json'),
    path('api/add/<str:id_product>/', wishlist_add_view_json, name='wishlist_add_view_json'),
    path('api/del/<str:id_product>/', wishlist_del_view_json, name='wishlist_del_view_json'),
    path('remove/<str:id_product>/', wishlist_remove_view, name="wishlist_remove_view"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from random import random
from django.http import HttpResponse
from app_datetime.views import datetime_view, dynamic_datetime_view
from app_weather.views import weather_view


def random_view(request):
    if request.method == "GET":
        data = random()
        return HttpResponse(data)


def dynamic_random_view(request):
    if request.method == "GET":
        script = '''
            <script>
                function updateNumber() {
                    let randomNum = Math.random();
                    document.getElementById("random").innerText = randomNum;
                }
                setInterval(updateNumber, 1000);
                window.onload = updateNumber;
            </script>
            <body>
                <h1>Случайное число: <span id="random">Загрузка...</span></h1>
            </body>
        '''
        return HttpResponse(script)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('random/', random_view),
    path('dynamic_random/', dynamic_random_view),
    path('datetime/', datetime_view),
    path('dynamic_datetime/', dynamic_datetime_view),
    path('weather/', weather_view),
    path('', include('app_store.urls')),
    path('login/', include('app_login.urls')),
    path('wishlist/', include('app_wishlist.urls')),
]

app_store/views.py
from django.http import JsonResponse, HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from .models import DATABASE
from logic.services import filtering_category
from logic.control_cart import view_in_cart, add_to_cart, remove_from_cart
from django.shortcuts import redirect
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required


def product_view_json(request):
    if request.method == "GET":
        id_ = request.GET.get('id')
        if id_:
            if id_ in DATABASE:
                return JsonResponse(DATABASE[id_], json_dumps_params={'ensure_ascii': False, 'indent': 4})
            return HttpResponseNotFound("Данного продукта нет в базе данных")

        category_key = request.GET.get("category")
        ordering_key = request.GET.get("ordering")
        reverse = request.GET.get("reverse", "false").lower() == "true"

        if category_key:
            data = filtering_category(DATABASE, category_key, ordering_key, reverse)
        elif ordering_key:
            data = filtering_category(DATABASE, ordering_key=ordering_key, reverse=reverse)
        else:
            data = list(DATABASE.values())

        return JsonResponse(data, safe=False, json_dumps_params={'ensure_ascii': False, 'indent': 4})


def shop_view(request):
    if request.method == "GET":
        # Обработка фильтрации из параметров запроса
        category_key = request.GET.get("category")
        if ordering_key := request.GET.get("ordering"):
            if request.GET.get("reverse") in ('true', 'True'):
                data = filtering_category(DATABASE, category_key, ordering_key, True)
            else:
                data = filtering_category(DATABASE, category_key, ordering_key)
        else:
            data = filtering_category(DATABASE, category_key)
        return render(request, 'app_store/shop.html',
                      context={"products": data,
                               "category": category_key})


def product_page_view(request, page):
    if request.method == "GET":
        # Ищем текущий товар
        product = None
        for data in DATABASE.values():
            if data['html'] == page:
                product = data
                break

        if not product:
            return HttpResponse(status=404)

        # Находим товары той же категории
        category = product["category"]

        other_products = [
            p for p in DATABASE.values()
            if p["category"] == category and p["html"] != page
        ][:4]

        return render(
            request,
            "app_store/product.html",
            context={
                "product": product,
                "other_products": other_products,
            }
        )


@login_required(login_url='app_login:login_view')
def cart_view_json(request):
    username = get_user(request).username
    data = view_in_cart(username)
    return JsonResponse(data, json_dumps_params={'ensure_ascii': False, 'indent': 4})


@login_required(login_url='app_login:login_view')
def cart_add_view_json(request, id_product):
    username = get_user(request).username
    result = add_to_cart(id_product, username)
    if result:
        return JsonResponse({"answer": "Продукт успешно добавлен в корзину"},
                            json_dumps_params={'ensure_ascii': False})
    return JsonResponse({"answer": "Неудачное добавление в корзину"},
                        status=404, json_dumps_params={'ensure_ascii': False})


@login_required(login_url='app_login:login_view')
def cart_del_view_json(request, id_product):
    username = get_user(request).username
    result = remove_from_cart(id_product, username)
    if result:
        return JsonResponse({"answer": "Продукт успешно удалён из корзины"},
                            json_dumps_params={'ensure_ascii': False})
    return JsonResponse({"answer": "Неудачное удаление из корзины"},
                        status=404, json_dumps_params={'ensure_ascii': False})


@login_required(login_url='app_login:login_view')
def cart_view(request):
    if request.method == "GET":
        username = get_user(request).username
        data = view_in_cart(username)[username]

        products = []
        for product_id, quantity in data['products'].items():
            product = DATABASE[product_id].copy()
            product["quantity"] = quantity
            product["price_total"] = "{:.2f}".format(quantity * product["price_after"])
            product["url"] = f'app_store/images/{product["url"].split("/")[-1]}'
            if product["price_after"] < product["price_before"]:
                product["discount"] = int((product["price_before"] - product["price_after"]) / product["price_before"] * 100)
            else:
                product["discount"] = None
            products.append(product)

        return render(request, "app_store/cart.html", context={"products": products})


@login_required(login_url='app_login:login_view')
def cart_buy_now_view(request, id_product):
    if request.method == "GET":
        username = get_user(request).username
        result = add_to_cart(id_product, username)
        if result:
            return redirect("app_store:cart_view")

        return HttpResponseNotFound("Неудачное добавление в корзину")


@login_required(login_url='app_login:login_view')
def cart_remove_view(request, id_product):
    if request.method == "GET":
        username = get_user(request).username
        # Вызов функции удаления из корзины
        result = remove_from_cart(id_product, username)
        if result:
            # Перенаправляем пользователя обратно в корзину
            return redirect("app_store:cart_view")

        return HttpResponseNotFound("Неудачное удаление из корзины")


def coupon_check_view(request, name_coupon):
    # DATA_COUPON - база данных купонов
    DATA_COUPON = {
        "coupon": {
            "discount": 10,
            "is_valid": True
        },
        "coupon_old": {
            "discount": 20,
            "is_valid": False
        },
    }

    if request.method == "GET":
        # Проверяем, есть ли купон в базе
        coupon = DATA_COUPON.get(name_coupon)
        if coupon:
            # Если купон найден, возвращаем JSON с информацией о скидке и действительности
            return JsonResponse({
                "discount": coupon["discount"],
                "is_valid": coupon["is_valid"]
            })
        else:
            # Если купон не найден, возвращаем 404
            return HttpResponseNotFound("Неверный купон")


def delivery_estimate_view(request):
    DATA_PRICE = {
        "Россия": {
            "Москва": {"price": 90},
            "Санкт-Петербург": {"price": 78},
            "fix_price": 100,  # для всех остальных городов России
        },
    }

    if request.method == "GET":
        country = request.GET.get('country')
        city = request.GET.get('city')

        if not country:
            return HttpResponseNotFound("Неверные данные")

        country_data = DATA_PRICE.get(country)
        if not country_data:
            return HttpResponseNotFound("Неверные данные")

        # Если город есть в базе — возвращаем цену
        if city in country_data:
            return JsonResponse({"price": country_data[city]["price"]})
        # Если города нет в базе, но есть fix_price — возвращаем фиксированную цену
        elif "fix_price" in country_data:
            return JsonResponse({"price": country_data["fix_price"]})
        else:
            return HttpResponseNotFound("Неверные данные")

app_store/templates/app_store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %} <!-- Блок для названия страницы-->

    {% endblock %}

    {% block head %} <!-- Блок ссылок в head-->
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

	<link type="image/x-icon" href="static/images/favicon.png" rel="shortcut icon">
	<link rel="stylesheet" href="{% static 'app_store/css/open-iconic-bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/aos.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/ionicons.min.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/bootstrap-datepicker.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/jquery.timepicker.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/flaticon.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/icomoon.css' %}">
	<link rel="stylesheet" href="{% static 'app_store/css/style.css' %}">
    {% endblock %}
</head>
<body class="goto-here">
    {% block header %} <!-- Блок для header страницы с данными магазина-->
    <div class="py-1 bg-primary">
		<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">+ 7 (812) 123 45 678</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">mystore@email.ru</span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
						    <span class="text">Доставка в течении 3-5 рабочих дней. Бесплатный возврат</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
    {% endblock %}

    {% block nav %} <!-- Блок для навигационной панели страницы магазина-->
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="#">Vegefoods</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Навигация
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item"><a href="{% url 'app_store:shop_view' %}" class="nav-link">Магазин</a>
			  <li class="nav-item"><a href="{% url 'app_wishlist:wishlist_view' %}"  class="nav-link">Избранное</a>
			  <li class="nav-item"><a href="{% url 'app_store:cart_view' %}" class="nav-link">Корзина</a>
				{% if user.is_authenticated %}
				<li class="nav-item"><a href="{% url 'app_login:logout_view'%}" class="nav-link">Выйти из аккаунта</a>
				<li class="nav-item"><a class="nav-link">Привет {{user.username}}!</a>
				{% else %}
				<li class="nav-item"><a href="{% url 'app_login:login_view'%}" class="nav-link">Войти в аккаунт</a>
				{% endif %}
	        </ul>
	      </div>
	    </div>
	  </nav>
    {% endblock %}

    {% block content %} <!-- Блок для уникального содержимого страницы-->

    {% endblock %}

    {% block news %} <!-- Блок для новостной панели-->
     <section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Подпишись на новости</h2>
          	<span>Получайте по электронной почте обновления о наших последних магазинах и специальных предложениях</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Введите ваш email">
                <input type="submit" value="Подписаться" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}

    {% block footer %} <!-- Блок для нижней панели страницы-->
     <footer class="ftco-footer ftco-section">
      <div class="container">
      	<div class="row">
      		<div class="mouse">
				<a href="#" class="mouse-icon">
					<div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
				</a>
			</div>
      	</div>
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vegefoods</h2>
              <p><i>Зеленый выбор для здоровой жизни!</i></p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-telegram"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-vk"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-whatsapp"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Навигация</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Магазин</a></li>
                <li><a href="#" class="py-2 d-block">О нас</a></li>
                <li><a href="#" class="py-2 d-block">Блог</a></li>
                <li><a href="#" class="py-2 d-block">Связаться с нами</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Помощь</h2>
              <div class="d-flex">
	              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
	                <li><a href="#" class="py-2 d-block">Информация о доставке</a></li>
	                <li><a href="#" class="py-2 d-block">Возврат и Обмен</a></li>
	                <li><a href="#" class="py-2 d-block">Условия и Положения</a></li>
	                <li><a href="#" class="py-2 d-block">Политика конфиденциальности</a></li>
	              </ul>
	              <ul class="list-unstyled">
	                <li><a href="#" class="py-2 d-block">Вопрос - ответ</a></li>
	                <li><a href="#" class="py-2 d-block">Контакты</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Остались вопросы?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">Россия, г. Санкт-Петербург, ул. Ответов на вопросы, д.1</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+ 7 (812) 123 45 678</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.ru</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Авторские права &copy;<script>document.write(new Date().getFullYear());</script> Все права защищены | Этот шаблон сделан с <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
          </div>
        </div>
      </div>
    </footer>
    {% endblock %}

    {% block scripts %} <!-- Блок для загрузки javascript страницы-->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

  	<script src="{% static 'app_store/js/jquery.min.js' %}"></script>
	<script src="{% static 'app_store/js/jquery-migrate-3.0.1.min.js' %}"></script>
	<script src="{% static 'app_store/js/popper.min.js' %}"></script>
	<script src="{% static 'app_store/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'app_store/js/jquery.easing.1.3.js' %}"></script>
	<script src="{% static 'app_store/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'app_store/js/jquery.stellar.min.js' %}"></script>
	<script src="{% static 'app_store/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'app_store/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'app_store/js/aos.js' %}"></script>
	<script src="{% static 'app_store/js/jquery.animateNumber.min.js' %}"></script>
	<script src="{% static 'app_store/js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'app_store/js/scrollax.min.js' %}"></script>
	<script src="{% static 'app_store/js/google-map.js' %}"></script>
	<script src="{% static 'app_store/js/main.js' %}"></script>
    {% endblock %}

    {% block custom_scripts %}  <!-- Блок для загрузки дополнительного кода встроенного в html-->

    {% endblock %}
</body>
</html>

app_store/templates/app_store/shop.html
{% extends 'app_store/base.html' %}
{%load static%}

{% block title %}
    <title>Интернет-магазин здоровых продуктов</title>
{% endblock %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'app_store/images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"></span></p>
            <h1 class="mb-0 bread">Продукты</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					{% if category is None %}
						<li><a href="{% url 'app_store:shop_view' %}" class="active">Все</a></li>
						{% else %}
						<li><a href="{% url 'app_store:shop_view' %}">Все</a></li>
						{% endif %}
						{% if category == 'Овощи' %}
						<li><a href="{% url 'app_store:shop_view' %}?category={{category}}" class="active">Овощи</a></li>
						{% else %}
						<li><a href="{% url 'app_store:shop_view' %}?category=Овощи">Овощи</a></li>
						{% endif %}
						{% if category == 'Фрукты' %}
						<li><a href="{% url 'app_store:shop_view' %}?category={{category}}" class="active">Фрукты</a></li>
						{% else %}
						<li><a href="{% url 'app_store:shop_view' %}?category=Фрукты">Фрукты</a></li>
						{% endif %}
						{% if category == 'Соки' %}
						<li><a href="{% url 'app_store:shop_view' %}?category={{category}}" class="active">Соки</a></li>
						{% else %}
						<li><a href="{% url 'app_store:shop_view' %}?category=Соки">Соки</a></li>
						{% endif %}
						{% if category == 'Семена' %}
						<li><a href="{% url 'app_store:shop_view' %}?category={{category}}" class="active">Семена</a></li>
						{% else %}
						<li><a href="{% url 'app_store:shop_view' %}?category=Семена">Семена</a></li>
						{% endif %}
    				</ul>
    			</div>
    		</div>
			<div class="row">
				{% for product in products %}
				<div class="col-md-6 col-lg-3 ftco-animate">
					<div class="product">
						<a href="{% url 'app_store:product_page_view' product.html %}" class="img-prod">
							<img class="img-fluid" src="{% static product.url %}" alt="{{ product.name }}">
							{% if product.discount %}
							<span class="status">{{ product.discount }}%</span>
							{% else %}
							<div class="overlay"></div>
							{% endif %}
						</a>
						<div class="text py-3 pb-4 px-3 text-center" style="height: 100px;">
							<h3><a href="{% url 'app_store:product_page_view' product.html %}">{{ product.name }}</a></h3>
							<div class="d-flex">
								<div class="pricing">
									<p class="price">
										{% if product.discount %}
										<span class="mr-2 price-dc">&#x20bd {{ product.price_before }}</span>
										<span class="price-sale">&#x20bd {{ product.price_after }}</span>
										{% else %}
										<span>&#x20bd {{ product.price_before }}</span>
										{% endif %}
									</p>
								</div>
							</div>
							<div class="bottom-area d-flex px-3">
								<div class="m-auto d-flex">
									<a href="#" class="add-to-cart d-flex justify-content-center align-items-center text-center" data-product-id="{{ product.id }}">
										<span><i class="ion-ios-add-circle-outline" data-product-id="{{ product.id }}"></i></span>
									</a>
									<a href="{% url 'app_store:buy_now' product.id %}" class="buy-now d-flex justify-content-center align-items-center mx-1">
										<span><i class="ion-ios-cart"></i></span>
									</a>
									<a href="#" class="heart d-flex justify-content-center align-items-center">
										<span><i class="ion-ios-heart-empty" data-product-id="{{ product.id }}" data-state="inactive" data-action="toggle"></i></span>
									</a>
								</div>
								<div class="custom-popup-message" data-product-id="{{ product.id }}"></div>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
		<div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    </section>
{% endblock %}

{% block custom_scripts %}
    <!-- Блок дополнительных пользовательских скриптов -->
    <script src="{% static 'app_store/js/appAddToCard.js' %}"></script>
    <script src="{% static 'app_store/js/appAddToWishlist.js' %}"></script>
{% endblock %}